name: tactic_design_system_package
description: "A private Flutter design system package."
version: 0.0.1
homepage: https://github.com/suojae/tactic-design-system-package

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
